//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaasOne.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaasOne.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id;en-US;de-DE;es-ES;fr-FR
        ///fin_pf_viewColumn_after_mkt_price_and_time;Last Trd Time &amp; Price (Aft Mkt);Zeit / Kurs (nachbörsl.);Ultima transacción y precio (Post Mercado);Cours dernier (aprés Bourse)
        ///fin_pf_viewColumn_after_mkt_change;After Mkt Chg;Nachbörsl. Veränd;Cambio post merc;Var. aprés Bourse
        ///fin_pf_viewColumn_after_mkt_change_and_percent;After Mkt Chg &amp; %;Nachbörsl. Veränd ;Cambio post merc y %;Var. et % (aprés Bourse)
        ///fin_pf_viewColumn_after_mkt_percent_change;Aft Mkt % Chg;Nachbörsl. Veränd. ( [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string localization {
            get {
                return ResourceManager.GetString("localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;!--
        /// ******************************************************************************
        /// ** 
        /// **  Yahoo! Managed
        /// **  Written by Marius Häusler 2012
        /// **  It would be pleasant, if you contact me when you are using this code.
        /// **  Contact: YahooFinanceManaged@gmail.com
        /// **  Project Home: http:code.google.com/p/yahoo-finance-managed/
        /// **  
        /// ******************************************************************************
        /// **  
        /// **  Copyright 2012 Marius Häusler
        /// ** [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string market {
            get {
                return ResourceManager.GetString("market", resourceCulture);
            }
        }
    }
}
